config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "about", to: "pages#about"
  # get "admin_users_index", to: "users#admin_users_index"

  resources :users_admin, :controller => 'users', only: [:index, :create, :update, :destroy]
  post "update_admin", to: "users#update_admin"

  resources :divisions, only: [:index, :create, :update, :destroy, :edit] do
    resources :categories, only: [:edit, :create, :destroy]
  end

  # divisions
  post "division_update_api", to: "divisions#update_api"

  # categories
  post "category_new_api", to: "categories#new_api"
  post "category_update_api", to: "categories#update_api"
  post "category_destroy_api", to: "categories#destroy_api"
  # company_skills
  post "company_skill_new_api", to: "company_skills#new_api"
  post "company_skill_update_api", to: "company_skills#update_api"
  post "company_skill_destroy_api", to: "company_skills#destroy_api"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/divisions_controller.rb
require 'open-uri'

class DivisionsController < ApplicationController
	before_action :set_division, only: [:update, :destroy]

	def index
		@user_token = session["authentication_token"]
		current_user_email = current_user.email

		url = "http://localhost:3000/api/v1/divisions?user_email=#{current_user_email}&user_token=#{@user_token}"

		html_file = open(url).read
		@divisions = JSON.parse(html_file)
	end

	def update_api
		id = params["id"]
		name = params["name"]

		user_token = session["authentication_token"]
		current_user_email = current_user.email

		api_url = "http://localhost:3000/api/v1/divisions/#{id}?user_email=#{current_user_email}&user_token=#{user_token}"

		response = HTTParty.patch(
			api_url, body: {
				division: {
					id: id, name: name
				}
			}
		)
		JSON.parse(response.body)

		redirect_to divisions_path
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  	
  end

  def about
  	raise
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	def create
		super
		user_info = sign_user_into_api
		session['authentication_token'] = user_info["authentication_token"]
	end

	private

	def sign_user_into_api
		# after devise sign in, we have a params with [:user][:email], [:user][:password]
		email = user_params[:email]
		password = encrypt_password(user_params[:password])

		api_url = 'http://localhost:3000/users/sign_in.json'
		# .json this is to force devise to send us a json response, instead of the normal redirect 
		response = HTTParty.post(
			api_url, body: {
				user: {email: email, password: password}
			}
		)
		JSON.parse(response.body)
	end

	def encrypt_password(str)
	  cipher_salt1 = 'some-random-salt-'
	  cipher_salt2 = 'another-random-salt-'
	  cipher = OpenSSL::Cipher.new('AES-128-ECB').encrypt
	  cipher.key = OpenSSL::PKCS5.pbkdf2_hmac_sha1(cipher_salt1, cipher_salt2, 20_000, cipher.key_len)
	  encrypted = cipher.update(str) + cipher.final
	  encrypted.unpack('H*')[0].upcase
	end

	def user_params
		params.require(:user).permit(:email, :password)
	end 

end

app/controllers/users_controller.rb
require 'open-uri'

class UsersController < ApplicationController
	def index
		user_token = session["authentication_token"]
	    current_user_email = current_user.email

	  	url = "http://localhost:3000/api/v1/users?user_email=#{current_user_email}&user_token=#{user_token}"

	  	html_file = open(url).read
	  	json_response = JSON.parse(html_file)

	  	users = json_response
	  	@admins = users.select { |user_hash| user_hash["admin"] }
	  	@employees = users.reject { |user_hash| user_hash["admin"] }
	  	@divisions = users.map { |user_hash| [user_hash["division"]["name"], user_hash["division"]["id"]] }.uniq!

	  	@user = User.new
	end

	def create
		user_token = session["authentication_token"]
	    current_user_email = current_user.email

	  	api_url = "http://localhost:3000/api/v1/users?user_email=#{current_user_email}&user_token=#{user_token}"

	  	html_file = open(api_url).read
	  	json_response = JSON.parse(html_file)
	  	emails = json_response

	  	emails = emails.map { |email_hash| email_hash["email"] }

	  	email = user_params[:email]
	  	password = encrypt_password(user_params[:password])

	  	is_included = emails.include? email

	  	if is_included
	  		# render whatever
	  	else
	  		user = User.new(email: email, password: password)
	  		user.save
	  	
		  	create_url = "http://localhost:3000/api/v1/users?user_email=#{current_user_email}&user_token=#{user_token}"
		  	# make post request to the other db and save it
		  	response = HTTParty.post(create_url.to_str, 
		  	    body: { 
		  	    	email: email, 
		  	        password: password, 
		  	    }.to_json,
		  	    :headers => { 
		  	    	'Content-Type' => 'application/json',
		  	    }
		  	)
		  	JSON.parse(response.body)
		end
		redirect_to users_admin_index_path
	end

	def update_admin
		user_token = session["authentication_token"]
	    current_user_email = current_user.email

		user_id = params["user_id"]

		update_url = "http://localhost:3000/api/v1/users/#{user_id}//update_admin?user_email=#{current_user_email}&user_token=#{user_token}"
		# make patch request to the other db and save it
		response = HTTParty.patch(update_url.to_str,
		    :headers => { 
		    	'Content-Type' => 'application/json',
		    }
		)
		JSON.parse(response.body)
		redirect_to users_admin_index_path
	end

	def update
		user_token = session["authentication_token"]
	    current_user_email = current_user.email

		user_id = params["id"]
		email = params["email"]

		update_url = "http://localhost:3000/api/v1/users/#{user_id}?user_email=#{current_user_email}&user_token=#{user_token}"
		# make patch request to the other db and save it
		response = HTTParty.patch(update_url.to_str,
			body: {
		  	    email: email, 
		  	}.to_json,
		    :headers => { 
		    	'Content-Type' => 'application/json',
		    }
		)
		JSON.parse(response.body)
		redirect_to users_admin_index_path
	end

	def destroy
		user_token = session["authentication_token"]
	    current_user_email = current_user.email

		user_id = params["id"]

		update_url = "http://localhost:3000/api/v1/users/#{user_id}?user_email=#{current_user_email}&user_token=#{user_token}"
		# make patch request to the other db and save it
		response = HTTParty.delete(update_url.to_str,
			body: {
		  	    id: user_id, 
		  	}.to_json,
		    :headers => { 
		    	'Content-Type' => 'application/json',
		    }
		)
		JSON.parse(response.body)
		redirect_to users_admin_index_path
	end

	private



	def user_params
	  params.require(:user).permit(:email, :password)

	end

	def encrypt_password(str)
	  cipher_salt1 = 'some-random-salt-'
	  cipher_salt2 = 'another-random-salt-'
	  cipher = OpenSSL::Cipher.new('AES-128-ECB').encrypt
	  cipher.key = OpenSSL::PKCS5.pbkdf2_hmac_sha1(cipher_salt1, cipher_salt2, 20_000, cipher.key_len)
	  encrypted = cipher.update(str) + cipher.final
	  encrypted.unpack('H*')[0].upcase
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for [division,category] do |f| %>
	<%= f.input :name, label: false %>
	<%= f.button :submit, class: "btn-submit" %>
<% end %>

app/views/categories/_form_tag.html.erb
<% if (defined?(name)).nil? %>
	<%= form_tag category_new_api_path, class: "edit-form" do %>
	  <%= hidden_field_tag :division_id, division_id %>
	  <%= label_tag :name, "New category name", class: "label" %>
	  <%= text_field_tag :name %>
	  <%= submit_tag "Update", class: "submit-btn" %>
	<% end %>
<% else %>
	<%= form_tag category_update_api_path, class: "edit-form" do %>
	  <%= hidden_field_tag :id, id %>
	  <%= label_tag :name, "New category name", class: "label" %>
	  <%= text_field_tag :name, name %>
	  <%= submit_tag "Update", class: "submit-btn" %>
	<% end %>
<% end %>

app/views/categories/_html_form.html.erb
<form novalidate="novalidate" action="/divisions/<%= division_id %>/categories/<%= id %>" method="post">
  <input type="hidden" name="utf8" type="hidden" value="✓">
  <input type="hidden" name="_method" value="patch">
  <!-- 
  <input type="hidden" name="authentication_token" value="<%= @user_token %>">
  -->

  New name:<br>
  <input type="text" name="name" value="<%= name %>"><br>
  <input type="hidden" name="division_id" value="<%= division_id %>"><br>
  <input type="hidden" name="id" value="<%= id %>"><br>
  <input type="submit" value="Submit">
</form>

app/views/company_skills/_form.html.erb
<%= simple_form_for [category, company_skill] do |f| %>
	<%= f.input :name %>
	<%= f.button :submit, class: "btn-submit" %>
<% end %>

app/views/company_skills/_form_tag.html.erb
<% if (defined?(name)).nil? %>
	<%= form_tag company_skill_new_api_path, class: "edit-form" do %>
	  <%= hidden_field_tag :category_id, category_id %>
	  <%= label_tag :name, "Add new company skill", class: "label" %>
	  <%= text_field_tag :name %>

	  <%= submit_tag "Sign in", class: "submit-btn" %>
	<% end %>
<% else %>
	<%= form_tag company_skill_update_api_path, class: "edit-form" do %>
	  <%= hidden_field_tag :id, id %>

	  <%= label_tag :name, "Update company skill", class: "label" %>
	  <%= text_field_tag :name, name %>

	  <%= submit_tag "Sign in", class: "submit-btn" %>
	<% end %>
<% end %>

app/views/divisions/_categories-menu.html.erb
<div class="categories-menu-wrapper">
	<div class="categories-menu-content">
		
		<div class="categories">
			<% division_categories.each do |category| %>
				<div id="<%= category["id"] %>" class="category js-menu-category-name">
					<%= category["name"] %>
				</div>
			<% end %>
		</div>

		<div class="dropdown icon-gray-clickable">
			<div class="dropdown-toggle" id="dropdownMenuButtonEditCategory" data-toggle="dropdown">
				<div class="new-category-title">
					<i class="fa fa-plus" aria-hidden="true"></i>
					Add category
				</div>
			</div>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButtonEditCategory">
			    <div class="dropdown-content-edit-form">
					<%= render "categories/form_tag", division_id: id %>
			    </div>

			</div>
		</div>

	</div>
</div>

app/views/divisions/_division-category-header.html.erb
<div class="division-category-header-wrapper">
	<div id="division-category-name-id-<%= category_id %>" class="name">
		<%= category_name %>
	</div>

	<div class="dropdown icon-gray-clickable">
		<div class="dropdown-toggle" id="dropdownMenuButtonEditCategory" data-toggle="dropdown">
			<i class="fa fa-pencil-square-o icon" aria-hidden="true"></i>
		</div>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButtonEditCategory">
		    <div class="dropdown-content-edit-form">
				<%= render "categories/form_tag", division_id: division_id, id: category_id, name: category_name %>
		    </div>

		</div>
	</div>

	<%= link_to category_destroy_api_path(id: category_id), method: :post, class: "icon icon-gray-clickable" do %>
		<i class="fa fa-trash-o" aria-hidden="true"></i>
	<% end %>

	<!-- New company skill -->
	<div class="dropdown icon-gray-clickable">
		<div class="dropdown-toggle" id="dropdownMenuButtonEditCategory" data-toggle="dropdown">
			<i class="fa fa-plus icon" aria-hidden="true"></i>
		</div>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButtonEditCategory">
		    <div class="dropdown-content-edit-form">
				<%= render "company_skills/form_tag", category_id: category_id %>
		    </div>
		</div>
	</div>
</div>

app/views/divisions/_division.html.erb
<%= render "categories-menu", id: division["id"], division_categories: division["categories"] %>

<div class="company_skills-block">
	<%= render "header", name: division["name"], id: division["id"] %>
	<% division["categories"].each do |category| %>
		
		<%= render "division-category-header", category_name: category["name"], division_id: division["id"], category_id: category["id"], category_name: category["name"] %>

		<div class="company_skills">
			<%= render "division_company_skills", category_company_skills: category["company_skills"], category_id: category["id"] %>
		</div>
	<% end %>
</div>

app/views/divisions/_division_company_skills.html.erb
<% category_company_skills.each do |company_skill| %>
	<div class="company_skill-wrapper">
		<div class="name">
			<%= company_skill["name"] %>
		</div>

		<div class="dropdown">
			<div class="dropdown-toggle icon-gray-clickable" id="dropdownMenuButton" data-toggle="dropdown">
				<i class="fa fa-pencil-square-o icon" aria-hidden="true"></i>
			</div>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			    <div class="dropdown-content-edit-form">
			    	<%= render "company_skills/form_tag", category_id: category_id, id: company_skill["id"], name: company_skill["name"] %>
			    </div>
			</div>
		</div>

		<%= link_to company_skill_destroy_api_path(id: company_skill["id"]), { method: :post } do %>
			<i class="fa fa-trash-o icon-gray-clickable icon" aria-hidden="true"></i>
		<% end %>

	</div>
<% end %>

app/views/divisions/_form.html.erb
<%= simple_form_for division do |f| %>
	<%= f.input :name %>
	<%= f.submit %>
<% end %>

app/views/divisions/_form_tag.html.erb
<%= form_tag division_update_api_path, class: "edit-form" do %>
  <%= hidden_field_tag :id, id %>
  <%= label_tag :name, "New division name", class: "label" %>
  <%= text_field_tag :name, name %>
  <%= submit_tag "Update", class: "submit-btn" %>
<% end %>

app/views/divisions/_header.html.erb
<div class="header">
	<div class="title-wrapper">
		<div class="name">
			<%= name %>
		</div>

		<div class="dropdown icon-gray-clickable">
			<div class="edit dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown">
				<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
			</div>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			    <div class="dropdown-content-edit-form">
			    	<%= render "form_tag", id: id, name: name %>
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/divisions/_html_form.html.erb
<form action="/divisions/<%= id %>/edit" method="patch">
  New name:<br>
  <input type="text" name="name" value="<%= name %>"><br>
  <input type="hidden" name="id" value="<%= id %>"><br>
  <input type="submit" value="Submit">
</form>

app/views/divisions/edit.html.erb
<div class="edit-divisions-page">
	
	<div class="header">

		<div class="title-wrapper">
			<div class="name">
				<%= @division.name %>
			</div>

			<div class="dropdown">
				<div class="edit dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown">
					<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
				</div>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				    <div class="dropdown-content">
				    	<%= render "form", division: @division %>
				    </div>
				</div>
			</div>
		</div>
	</div>

	<div class="categories-company_skills-section">
		<div class="categories-block">
			<div class="new-category-title">
				<i class="fa fa-plus" aria-hidden="true"></i>
				Add category
			</div>

			<div class="new-category-form">
				<%= render "categories/form", division: @division, category: @category %>
			</div>

			<div class="categories">
				<% @division.categories.each do |category| %>
					<div class="category">
						<%= category.name %>
					</div>
				<% end %>
			</div>
		</div>
		<div class="company_skills-block">
			<% @division.categories.each do |category| %>
				<div class="category-wrapper">
					<div class="name">
						<%= category.name %>
					</div>

					<div class="dropdown">
						<div class="dropdown-toggle" id="dropdownMenuButtonEditCategory" data-toggle="dropdown">
							<i class="fa fa-pencil-square-o icon" aria-hidden="true"></i>
						</div>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButtonEditCategory">
						    <div class="dropdown-content">
						    	<%= render "categories/form", division: @division, category: category %>
						    </div>
						</div>
					</div>

					<%= link_to category_path(category), method: :delete, class: "icon" do %>
						<i class="fa fa-trash-o" aria-hidden="true"></i>
					<% end %>

					<div class="new-company-skill">
						<%= render "company_skills/form", category: category, company_skill: @company_skill %>
					</div>
				</div>

				<div class="company_skills">
					<% category.company_skills.each do |company_skill| %>
						<div class="company_skill-wrapper">
							<div class="name">
								<%= company_skill.name %>
							</div>

							<div class="dropdown">
								<div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown">
									<i class="fa fa-pencil-square-o icon" aria-hidden="true"></i>
								</div>
								<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								    <div class="dropdown-content">
								    	<%= render "company_skills/form", category: category, company_skill: company_skill %>
								    </div>
								</div>
							</div>

							<%= link_to category_company_skill_path(category, company_skill), method: :delete, data: { confirm: "Are you sure?" }, class: "icon" do %>
								<i class="fa fa-trash-o" aria-hidden="true"></i>
							<% end %>
						</div>
					<% end %>
				</div>

			<% end %>
		</div>

	</div>

</div>

app/views/divisions/index.html.erb
<div class="index-divisions-wrapper">
	<div class="index-divisions-content">
		<% @divisions.each_with_index do |division, index| %>
			<div id="content-division-id-<%= index %>" class="division-wrapper <%= 'hide' unless index == 0 %>">
				<%= render "division", division: division, divisions: @divisions %>
			</div>
		<% end %>
		<div class="divisions-menu">
			<div class="divisions-menu-content">
				<% @divisions.each_with_index do |division, index| %>
					<div id="<%= index %>" class="js-division-btn division-name <%= "btn-active-green" if index == 0 %>">
						<%= division["name"] %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WAY Book Admin</title>

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Satisfy|Gloria+Hallelujah" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

    <!-- jquery -->
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
    <%= javascript_include_tag "http://code.jquery.com/ui/1.8.19/jquery-ui.min.js" %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-page">
	<div class="admin-logo-wrapper">
		<div class="logo">
			<i class="fa fa-user-circle-o" aria-hidden="true"></i>
		</div>
		<div class="sentences">
			<div class="sentence">
				Hi, Admin!
			</div>
			<div class="sentence">
				Here you can manage all the users from WAY Book and all the skills :)
			</div>
		</div>
	</div>

	<% if user_signed_in? %>
		<div class="menu-home">
			<div class="card users">
				
			</div>
			<div class="card skills">
				
			</div>
		</div>
	<% else %>
		<div class="sign-in-wrapper">
			<%= form_for(:user, :url => session_path(:user), html: {class: "sign-in-form"}) do |f| %>
			  <%= f.text_field :email, placeholder: "frederik.müller@waygroup.de" %>
			  <%= f.password_field :password, placeholder: "password", class: "placeholder" %>
			  <div class="remember-me-wrapper">
				  <%= f.check_box :remember_me %>
				  <%= f.label :remember_me, class: "label-remember-me" %>
			  </div>
			  <%= f.submit 'Sign in', class: "submit-btn" %>
			  <%= link_to "Forgot your password?", new_password_path(:user) %>
			<% end %>
		</div>
	<% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/_edit_form.html.erb
<%= form_tag users_admin_path(id: user_id), method: :patch, class: "edit-form", id: user_id do %>
  <%= hidden_field_tag :id, user_id, id: "hidden-#{user_id}" %>
  <%= label_tag :email, "Email", class: "label" %>
  <%= text_field_tag :email, email, id: "input-#{user_id}" %>
  <%= submit_tag "Update", class: "submit-btn" %>
<% end %>

app/views/users/_new_form.html.erb
<%= simple_form_for user, :url => users_admin_index_path, :method => :post do |f| %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= submit_tag "Create user", class: "submit-btn" %>
<% end %>

app/views/users/_user_hash.html.erb
<div class="user-wrapper js-user-wrapper-<%= user_hash["division"]["id"] %>">
	<div class="email">
		<%= user_hash["email"] %>
	</div>
	<div class="icons">
		<%= link_to update_admin_path(user_id: user_hash["id"]), method: :post do %>
			<div class="admin icon">
				<% color = user_hash["admin"] ? "admin-green" : "admin-gray" %>
				<i class="fa fa-users <%= color %>" aria-hidden="true"></i>
			</div>
		<% end %>

		<!-- Update email -->
		<div class="dropdown edit icon">
			<div class="dropdown-toggle" id="dropdownMenuButtonEditCategory" data-toggle="dropdown">
				<i class="fa fa-pencil-square-o icon-gray" aria-hidden="true"></i>
			</div>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButtonEditCategory">
			    <div class="dropdown-content-edit-form">
					<%= render "edit_form", user_id: user_hash["id"], email: user_hash["email"] %>
			    </div>
			</div>
		</div>

		<%= link_to users_admin_path(id: user_hash["id"]), method: :delete, data: { confirm: "Are you sure?" } do %>
			<div class="delete icon">
				<i class="fa fa-trash-o icon-gray" aria-hidden="true"></i>
			</div>
		<% end %>
	</div>
</div>